-- Exploratory Data Analysis project

-- All the objects in the database 
select * from information_schema.tables

-- All the columns in the database
select * from information_schema.columns
where TABLE_NAME in ('dim_customers','dim_products','fact_sales')

-- UNDERSTANDING DIFFERENT DIMENSIONS IN THE DATA

-- All countries our customers come from
select distinct country from dim_customers

-- All categories from 'the major divisions'
select distinct category from dim_products

select distinct category, subcategory from dim_products
order by 1,2

select distinct category, subcategory, product_name from dim_products
order by 1,2,3

-- EXPLORING THE TIME RANGE IN THE DATA

-- Finding the date of the first and last order and their difference in years
select 
min(order_date) as first_order_date,
max(order_date) as last_order_date,
datediff(year, min(order_date), max(order_date)) as order_range_years
from fact_sales

-- Finding the youngest and oldest customer
select 
min(birthdate) as oldest_birthdate,
datediff(year, min(birthdate), getdate()) as oldest_age,
max(birthdate) as youngest_birthdate,
datediff(year, max(birthdate), getdate()) as youngest_age
from dim_customers

-- EXPLORING THE MEASURES IN THE DATA - finding the key metrics of the business (big numbers)

-- Finding the total sales
select sum(sales_amount) as total_sales from fact_sales

-- Finding how many items are sold
select sum(quantity) as total_quantity from fact_sales

-- Finding the average selling price
select avg(price) as avg_price from fact_sales

-- Finding the total number of orders
select count(distinct order_number) as total_orders from fact_sales

-- Finding the total number of products
select count(distinct product_name) as total_products from dim_products

-- Finding the total number of customers
select count(customer_key) as total_customers from dim_customers

-- Finding the total number of customers that has placed an order
select count(distinct customer_key) as total_customers from fact_sales

-- Generating a report that shows all key metrics of the business
select 'Total Sales' as measure_name, sum(sales_amount) as measure_value from fact_sales
union all
select 'Total Quantity', sum(quantity) from fact_sales
union all
select 'Average Price', avg(price) from fact_sales
union all
select 'Total number of orders', count(distinct order_number) from fact_sales
union all
select 'Total number of Products', count(distinct product_name) from dim_products
union all
select 'Total number of Customers', count(distinct customer_key) from fact_sales

-- MAGNITUDE ANALYSIS - GROUPING DIFFERENT MEASURES WITH DIMENSIONS

-- Finding total customers by countries
select 
country, 
count(customer_key) as total_customers
from dim_customers
group by country
order by 2 desc

-- Finding total customers by gender
select 
gender, 
count(customer_key) as total_customers
from dim_customers
group by gender
order by 2 desc

-- Finding total products by category
select 
category, 
count(product_id) as total_products
from dim_products
group by category
order by 2 desc

-- What is the average costs in each category?
select 
category, 
avg(cost) as avg_costs
from dim_products
group by category
order by 2 desc

-- What is the total revenue generated for each category?
select  
p.category,
sum(s.sales_amount) as total_revenue
from fact_sales as s
left join dim_products as p
on p.product_key = s.product_key
group by p.category
order by 2 desc

-- Find total revenue generated by each customer
select 
c.customer_key,
c.first_name,
c.last_name,
sum(s.sales_amount) as total_revenue
from fact_sales as s
left join dim_customers as c
on c.customer_key = s.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by 4 desc

-- What is the distribution of sold items across countries?
select 
c.country,
sum(s.quantity) as total_sold_items
from fact_sales as s
left join dim_customers as c
on c.customer_key = s.customer_key
group by 
c.country
order by 2 desc

-- RANKING ANALYSIS - order the values of dimensions by measure and top and bottom performers

-- Which 5 products generate the highest revenue?
select top 5 
p.product_id,
p.product_number,
p.product_name,
sum(s.sales_amount) as total_revenue
from fact_sales as s
left join dim_products as p
on p.product_key = s.product_key
group by 
p.product_id,
p.product_number,
p.product_name
order by 4 desc

-- what are the 5 worst-performing products in terms of sales?
select top 5 
p.product_id,
p.product_number,
p.product_name,
sum(s.sales_amount) as total_revenue
from fact_sales as s
left join dim_products as p
on p.product_key = s.product_key
group by 
p.product_id,
p.product_number,
p.product_name
order by 4 asc

-- best subcategories for revenue
select top 5 
p.subcategory,
sum(s.sales_amount) as total_revenue
from fact_sales as s
left join dim_products as p
on p.product_key = s.product_key
group by p.subcategory
order by 2 desc

-- top 10 customers who have generated the highest revenue
select top 10
c.customer_key,
c.first_name,
c.last_name,
sum(s.sales_amount) as total_revenue
from fact_sales as s
left join dim_customers as c
on c.customer_key = s.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by 4 desc

-- 3 customers with the fewest orders placed
select top 3
c.customer_key,
c.first_name,
c.last_name,
count(distinct order_number) as total_orders
from fact_sales as s
left join dim_customers as c
on c.customer_key = s.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by 4 asc